# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f528ee4ddff8c12a877fd4343e953cc81f5d2eb77f4c5accfa1ea056165e1d13cba7f0bc4fc9f3217a16a0d959b8d1957a761e79748db38503ec4b751e1378aa

test:
  secret_key_base: 4661fab13f92e5c53f983a4f0c7df2fd427ebea57ef7fb81c6b5ca52104f25a2be7ca503b79b910163c15b3d628b4727d2e4c5c1cb3c6e3dd8d5fa4de086a607

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
